### ISSUE TITLE
Error when disabling a addon

### ISSUE THREAD

**Issue by intruder0** [Eliote/SimpleAddonManager#34] opened 2023-11-10 14:24 UTC
Message: Interface/AddOns/SimpleAddonManager/Core.lua:336: bad argument #2 to 'DisableAddOn' (Usage: C_AddOns.DisableAddOn(name [, character]))
Time: Fri Nov 10 09:22:10 2023
Count: 2
Stack: Interface/AddOns/SimpleAddonManager/Core.lua:336: bad argument #2 to 'DisableAddOn' (Usage: C_AddOns.DisableAddOn(name [, character]))

Locals:

**Comment by Eliote** [comment] 2023-11-10 22:35
Duplicate of #33

**Closed by Eliote** 2023-11-10 22:35 UTC
