### ISSUE TITLE
[Feature Request] Add addons from a profile without replacing the current addons.

### ISSUE THREAD

**Issue by JoeyJFranklin** [Eliote/SimpleAddonManager#29] opened 2023-05-23 19:23 UTC
If you have addons A, B, C loaded and you choose PROFILE_TWO with D, E, F then A, B, C addons are disabled and D,E,F are enabled. My suggestion is to have an option to add PROFILE_TWO's addons D,E,F to A,B,C

**Comment by Eliote** [comment] 2023-05-24 03:00
Duplicate of #26

**Closed by Eliote** 2023-05-24 03:00 UTC
